### PR TITLE
fix typo:corrected Exmaple to Example

### LINKED ISSUE #3807: [DOC] fix typo in charts\vineyard\values.yaml
**Provide a link to that doc page:**
https://github.com/fluid-cloudnative/fluid/blob/master/charts/vineyard/values.yaml
**What is the defect and your suggestions on improvement:**
charts\vineyard\values.yaml:22:4: corrected "Exmaple" to "Example"
charts\vineyard\values.yaml:52:4: corrected "Exmaple" to "Example"

### PR DESCRIPTION
**Pull request by Cchen-77**
### Ⅰ. Describe what this PR does
Fixed #3807 
This pr is to corrected "Exmaple" to "Example" of file charts\vineyard\values.yaml:22:4 and 52:4

### CODE REVIEW

**Comment by LiYuhang9527** [comment]
look good to me

**Review by RongGu — APPROVED** [review]
/approve

**Pull request merged**
