### PR TITLE
Build docker images for customizing management namespace

### PR DESCRIPTION
**Pull request by cheyang**
### Ⅱ. Does this pull request fix one issue?

fixes #XXXX

### Ⅴ. Special notes for reviews

### CODE REVIEW

**Review by fengshunli — COMMENTED** [review]
version can be written as a variable and configured in values.yaml for reading

**Comment by TrafalgarZZZ** [comment]
/lgtm

@fengshunli ‘s suggestion also LGTM. But I'm not sure is it possible to define helm variable in values.yaml? I fail to parse` this `values.yaml`:

```
{{ $version := v0.9.0-xxxxx }}

dataset:
  controller:
    image: fluidcloudnative/dataset-controller:{{ $version }}
```

I found some [workaround](https://github.com/helm/helm/issues/2133#issuecomment-589695803) but IMO it looks even more confusing.  

I do find some alternatives like the YAML Anchors. The solution is to separate image and imageTag, and use [YAML anchors](https://helm.sh/docs/chart_template_guide/yaml_techniques/#yaml-anchors), like the following `values.yaml` snippet:

```
version: &version v0.9.0-601192e

dataset:
  replicas: 1
  controller:
    image: fluidcloudnative/dataset-controller
    imageTag: *version
```

Correspondingly in dataset controlelr's tempalte yaml, it should be modified like:
```
image: "{{ .Values.dataset.controller.image }}:{{ .Values.dataset.controller.imageTag }}"
```

**Review by TrafalgarZZZ — APPROVED** [review]

**Comment by fengshunli** [comment]
> 

It is usually configured using this variable

**Comment by TrafalgarZZZ** [comment]
@fengshunli Hi, I am still not sure which variable you're referring to. It seems you quote-replied an empty string. I've created an issue about the enhancement here ( #2732 ), we can continue our discussion under the issue.

**Pull request merged**
