### PR TITLE
Update the Copyright information in pkg/ddc/thin/ufs_internal.go

### PR DESCRIPTION
**Pull request by Twilight-Mirage**
### Ⅰ. Describe what this PR does

This pr is to update the Copyright information in the pkg/ddc/thin/ufs_internal.go file, specifically, to update the year from 2022 to 2023.

### Ⅱ. Does this pull request fix one issue?

NONE

### Ⅴ. Special notes for reviews

### CODE REVIEW

**Review by cheyang — APPROVED** [review]
/lgtm
/approve

**Comment by cheyang** [comment]
@Twilight-Mirage Please check  if you need to update so many files?

**Comment by Twilight-Mirage** [comment]
Sorry, maybe not. In fact, I forgot whether I had followed the notes provided by the TA, so I pushed again.
I think there might be a mistake. Maybe I'll open a new pull request, sorry again for the trouble.

**Pull request closed without merging**
