### PR TITLE
feat: update gomonkey version

### LINKED ISSUE #1012: [FEATURES]Support Running in Apple M1
**What feature you'd like to add:**
ENV: Apple M1 
While running below code,
```
 make test
```
will meet errors as below 
```
....
# github.com/agiledragon/gomonkey
../../../../pkg/mod/github.com/agiledragon/gomonkey@v2.0.2+incompatible/patch.go:163:10: undefined: buildJmpDirective
make: *** [vet] Error 1
```

Ref [gomonkey issue 38](https://github.com/agiledragon/gomonkey/issues/38)

Some changes needed
```
--- a/go.mod
+++ b/go.mod
@@ -1,9 +1,9 @@
 
 require (
-       github.com/agiledragon/gomonkey v2.0.2+incompatible
+       github.com/agiledragon/gomonkey/v2 v2.2.0

```

```
--- a/pkg/ddc/alluxio/cache_test.go
+++ b/pkg/ddc/alluxio/cache_test.go
@@ -4,7 +4,7 @@ import (
        "reflect"
        "testing"
 
-       . "github.com/agiledragon/gomonkey"
+       . "github.com/agiledragon/gomonkey/v2"

```

**Why is this feature needed:**
I am not sure if this needed. :-)

### PR DESCRIPTION
**Pull request by swartz-k**
Signed-off-by: swartz-k <9215868@gmail.com>

### Ⅰ. Describe what this PR does
Update gomonkey version for running && build on MACOS M1

### Ⅱ. Does this pull request fix one issue?
fixes #1012 

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.
No tests added.

### Ⅳ. Describe how to verify it
Exec command `make build`

### CODE REVIEW

**Comment by wsxiaozhang** [comment]
> Signed-off-by: swartz-k [9215868@gmail.com](mailto:9215868@gmail.com)
> 
> ### Ⅰ. Describe what this PR does
> Update gomonkey version for running && build on MACOS M1
> 
> ### Ⅱ. Does this pull request fix one issue?
> fixes #1012
> 
> ### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.
> No tests added.
> 
> ### Ⅳ. Describe how to verify it
> Exec command `make build`
> 
> ### Ⅴ. Special notes for reviews

@swartz-k what version of your macos? I can't make it on my M1 with big sur 11.4. Gomonkey has problem of "syscall.Mprotect panic: permission denied". The previous workaround seems not to work anymore. see
 https://github.com/eisenxp/macos-golink-wrapper/issues/1

**Comment by swartz-k** [comment]
>"syscall.Mprotect panic: permission denied". The previous workaround seems not to work anymore. see
> [eisenxp/macos-golink-wrapper#1](https://github.com/eisenxp/macos-golink-wrapper/issues/1)

hello, My OS is 11.6 and all running log as below
```
> make build
GO111MODULE=off /Users/joker/go/bin/controller-gen object:headerFile=./hack/boilerplate.go.txt paths="./..."
GO111MODULE=off go fmt ./...
GO111MODULE=off go list ./... | grep -v "vendor" | xargs go vet
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=off  go build -gcflags="-N -l" -a -o bin/dataset-controller -ldflags '-X github.com/fluid-cloudnative/fluid.version=v0.7.0 -X github.com/fluid-cloudnative/fluid.buildDate=2021-09-26_09:07:02 -X github.com/fluid-cloudnative/fluid.gitCommit=609640f02f6d5ab6f2a2436fcb146fabb1622adf -X github.com/fluid-cloudnative/fluid.gitTreeState=dirty -extldflags "-static"' cmd/dataset/main.go
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=off  go build -gcflags="-N -l" -a -o bin/alluxioruntime-controller -ldflags '-X github.com/fluid-cloudnative/fluid.version=v0.7.0 -X github.com/fluid-cloudnative/fluid.buildDate=2021-09-26_09:07:15 -X github.com/fluid-cloudnative/fluid.gitCommit=609640f02f6d5ab6f2a2436fcb146fabb1622adf -X github.com/fluid-cloudnative/fluid.gitTreeState=dirty -extldflags "-static"' cmd/alluxio/main.go
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=off  go build -gcflags="-N -l" -a -o bin/jindoruntime-controller -ldflags '-X github.com/fluid-cloudnative/fluid.version=v0.7.0 -X github.com/fluid-cloudnative/fluid.buildDate=2021-09-26_09:07:28 -X github.com/fluid-cloudnative/fluid.gitCommit=609640f02f6d5ab6f2a2436fcb146fabb1622adf -X github.com/fluid-cloudnative/fluid.gitTreeState=dirty -extldflags "-static"' cmd/jindo/main.go
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=off  go build -o bin/fluid-csi -ldflags '-X github.com/fluid-cloudnative/fluid.version=v0.7.0 -X github.com/fluid-cloudnative/fluid.buildDate=2021-09-26_09:07:40 -X github.com/fluid-cloudnative/fluid.gitCommit=609640f02f6d5ab6f2a2436fcb146fabb1622adf -X github.com/fluid-cloudnative/fluid.gitTreeState=dirty -extldflags "-static"' cmd/csi/main.go
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=off  go build -gcflags="-N -l" -a -o bin/fluid-webhook -ldflags '-X github.com/fluid-cloudnative/fluid.version=v0.7.0 -X github.com/fluid-cloudnative/fluid.buildDate=2021-09-26_09:07:42 -X github.com/fluid-cloudnative/fluid.gitCommit=609640f02f6d5ab6f2a2436fcb146fabb1622adf -X github.com/fluid-cloudnative/fluid.gitTreeState=dirty -extldflags "-static"' cmd/webhook/main.go
> echo $?
0
> go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/joker/Library/Caches/go-build"
GOENV="/Users/joker/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/joker/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/joker/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.17/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.17/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/joker/go/src/github.com/fluid-cloudnative/fluid/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/7p/lcf9_lgn2j3f17g83k994ypr0000gn/T/go-build3128026559=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by cheyang** [comment]
@swartz-k Are you able to run `make test` in your M1 laptop?

**Comment by swartz-k** [comment]
> @swartz-k Are you able to run `make test` in your M1 laptop?

Ops, I got some errors as below and almost are `permission denied`. Looks like cannot update gomonkey?
```
> make test |grep FAI
--- FAIL: TestQueryCacheStatus (0.00s)
--- FAIL: TestGetCacheHitStates (0.00s)
--- FAIL: TestGetHCFSStatus (0.00s)
FAIL	github.com/fluid-cloudnative/fluid/pkg/ddc/alluxio	0.358s
--- FAIL: TestAlluxioFileUtils_IsExist (0.00s)
FAIL	github.com/fluid-cloudnative/fluid/pkg/ddc/alluxio/operations	0.346s
--- FAIL: TestQueryCacheStatus (0.00s)
--- FAIL: TestGetCacheHitStates (0.00s)
--- FAIL: TestGetHCFSStatus (0.00s)
FAIL	github.com/fluid-cloudnative/fluid/pkg/ddc/goosefs	0.477s
--- FAIL: TestGooseFSFileUtils_IsExist (0.00s)
FAIL	github.com/fluid-cloudnative/fluid/pkg/ddc/goosefs/operations	0.459s
--- FAIL: TestQueryCacheStatus (0.00s)
--- FAIL: TestCreateDataLoadJob (0.00s)
FAIL	github.com/fluid-cloudnative/fluid/pkg/ddc/jindo	0.622s
--- FAIL: TestJindoFileUtils_exec (0.00s)
FAIL	github.com/fluid-cloudnative/fluid/pkg/ddc/jindo/operations	0.274s
--- FAIL: TestGenerateHelmTemplate (0.00s)
FAIL	github.com/fluid-cloudnative/fluid/pkg/utils/helm	0.467s
--- FAIL: TestCreateConfigMapFromFile (0.00s)
FAIL	github.com/fluid-cloudnative/fluid/pkg/utils/kubectl	0.475s
FAIL
make: *** [test] Error 1
```

**Comment by cheyang** [comment]
Did you try https://github.com/agiledragon/gomonkey/issues/10#issuecomment-842979716 ? Sorry, I don't have M1 laptop.

**Comment by swartz-k** [comment]
> Did you try [agiledragon/gomonkey#10 (comment)](https://github.com/agiledragon/gomonkey/issues/10#issuecomment-842979716) ? Sorry, I don't have M1 laptop.

Not work. Maybe I need to use this with docker.

**Review by littletiger123 — APPROVED** [review]
LGTM

**Comment by cheyang** [comment]
> > Did you try [agiledragon/gomonkey#10 (comment)](https://github.com/agiledragon/gomonkey/issues/10#issuecomment-842979716) ? Sorry, I don't have M1 laptop.
> 
> Not work. Maybe I need to use this with docker.

Could you check if it works with go.darwin-amd64.pkg ?

**Comment by swartz-k** [comment]
> > > Did you try [agiledragon/gomonkey#10 (comment)](https://github.com/agiledragon/gomonkey/issues/10#issuecomment-842979716) ? Sorry, I don't have M1 laptop.
> > 
> > 
> > Not work. Maybe I need to use this with docker.
> 
> Could you check if it works with go.darwin-amd64.pkg ?

It works. 
```
> make amd64-test
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=off  go list ./... | grep -v controller | grep -v e2etest | xargs go test  -gcflags=-l
?   	github.com/fluid-cloudnative/fluid	[no test files]
?   	github.com/fluid-cloudnative/fluid/api/v1alpha1	[no test files]
?   	github.com/fluid-cloudnative/fluid/cmd/alluxio	[no test files]
?   	github.com/fluid-cloudnative/fluid/cmd/csi	[no test files]
?   	github.com/fluid-cloudnative/fluid/cmd/dataset	[no test files]
?   	github.com/fluid-cloudnative/fluid/cmd/goosefs	[no test files]
?   	github.com/fluid-cloudnative/fluid/cmd/goosefs/app	[no test files]
?   	github.com/fluid-cloudnative/fluid/cmd/jindo	[no test files]
?   	github.com/fluid-cloudnative/fluid/cmd/webhook	[no test files]
?   	github.com/fluid-cloudnative/fluid/cmd/webhook/app	[no test files]
?   	github.com/fluid-cloudnative/fluid/hack/sdk	[no test files]
ok  	github.com/fluid-cloudnative/fluid/pkg/common	2.146s
?   	github.com/fluid-cloudnative/fluid/pkg/common/deprecated	[no test files]
?   	github.com/fluid-cloudnative/fluid/pkg/csi/fuse	[no test files]
?   	github.com/fluid-cloudnative/fluid/pkg/databackup	[no test files]
?   	github.com/fluid-cloudnative/fluid/pkg/dataload	[no test files]
?   	github.com/fluid-cloudnative/fluid/pkg/ddc	[no test files]
ok  	github.com/fluid-cloudnative/fluid/pkg/ddc/alluxio	6.070s
ok  	github.com/fluid-cloudnative/fluid/pkg/ddc/alluxio/operations	2.257s
ok  	github.com/fluid-cloudnative/fluid/pkg/ddc/base	2.316s
?   	github.com/fluid-cloudnative/fluid/pkg/ddc/base/mock	[no test files]
ok  	github.com/fluid-cloudnative/fluid/pkg/ddc/base/portallocator	2.007s
ok  	github.com/fluid-cloudnative/fluid/pkg/ddc/goosefs	6.453s
ok  	github.com/fluid-cloudnative/fluid/pkg/ddc/goosefs/operations	2.268s
ok  	github.com/fluid-cloudnative/fluid/pkg/ddc/jindo	6.001s
ok  	github.com/fluid-cloudnative/fluid/pkg/ddc/jindo/operations	31.912s
?   	github.com/fluid-cloudnative/fluid/pkg/runtime	[no test files]
ok  	github.com/fluid-cloudnative/fluid/pkg/utils	1.563s
ok  	github.com/fluid-cloudnative/fluid/pkg/utils/dataset/lifecycle	5.337s
ok  	github.com/fluid-cloudnative/fluid/pkg/utils/dataset/volume	1.596s
ok  	github.com/fluid-cloudnative/fluid/pkg/utils/docker	1.269s
ok  	github.com/fluid-cloudnative/fluid/pkg/utils/helm	1.236s
ok  	github.com/fluid-cloudnative/fluid/pkg/utils/kubeclient	2.050s
ok  	github.com/fluid-cloudnative/fluid/pkg/utils/kubectl	1.213s
ok  	github.com/fluid-cloudnative/fluid/pkg/utils/tieredstore	1.550s
ok  	github.com/fluid-cloudnative/fluid/pkg/webhook	1.976s
?   	github.com/fluid-cloudnative/fluid/pkg/webhook/handler	[no test files]
ok  	github.com/fluid-cloudnative/fluid/pkg/webhook/plugins	1.650s
ok  	github.com/fluid-cloudnative/fluid/pkg/webhook/plugins/prefernodeswithcache	1.394s
ok  	github.com/fluid-cloudnative/fluid/pkg/webhook/plugins/prefernodeswithoutcache	1.421s
ok  	github.com/fluid-cloudnative/fluid/pkg/webhook/plugins/requirenodewithfuse	1.110s
?   	github.com/fluid-cloudnative/fluid/pkg/webhook/scheduler/mutating	[no test files]
> go version
go version go1.17.1 darwin/amd64
```

**Comment by cheyang** [comment]
@swartz-k I think this fix is not able to crack the issue #1012 , so  I prefer to close this PR. WDYT?  

Btw thanks very much for your contributions. If you'd like  add [faq.md](https://github.com/fluid-cloudnative/fluid/blob/master/docs/en/userguide/faq.md) for this info, I will be very appreciated.

**Comment by swartz-k** [comment]
> @swartz-k I think this fix is not able to crack the issue #1012 , so I prefer to close this PR. WDYT?
> 
> Btw thanks very much for your contributions. If you'd like add M1 limitation in [faq.md](https://github.com/fluid-cloudnative/fluid/blob/master/docs/en/userguide/faq.md) for this info, I will be very appreciated.

sure

**Pull request closed without merging**
