### PR TITLE
transformer -> transformers

### LINKED ISSUE #4024: [DOC]change transfromer to transformers
**Provide a link to that doc page:**
https://github.com/fluid-cloudnative/fluid/blob/master/pkg/ddc/jindo/load_data.go
**What is the defect and your suggestions on improvement:**
change transfromer to transformers

### PR DESCRIPTION
**Pull request by starriver030515**
### Ⅰ. Describe what this PR does
fixes #4024 
this pr is to corrected 'transformer' to 'transformers' of the file https://github.com/fluid-cloudnative/fluid/blob/master/pkg/ddc/jindo/load_data.go

### CODE REVIEW

**Comment by LiYuhang9527** [comment]
transfromer -> transformers, please modify your pr

**Comment by starriver030515** [comment]
> transfromer -> transformers, please modify your pr

what does it mean?

**Comment by starriver030515** [comment]
> transfromer -> transformers, please modify your pr

Is it ok now?

**Comment by LiYuhang9527** [comment]
> > transfromer -> transformers, please modify your pr
> 
> what does it mean?

你没有按照任务要求正确修改拼写错误，应该把transfromer 改成transformers,  但是你改成了transfromers，所以你要重新修改提交一下

**Comment by starriver030515** [comment]
> > > transfromer -> transformers, please modify your pr
> > 
> > 
> > what does it mean?
> 
> 你没有按照任务要求正确修改拼写错误，应该把transfromer 改成transformers, 但是你改成了transfromers，所以你要重新修改提交一下

yeah, i am blind

**Pull request closed without merging**
