### PR TITLE
support setting affinity when using Jindo Dataload

### PR DESCRIPTION
**Pull request by allenhaozi**
Signed-off-by: mahao <allenhaozi@gmail.com>

### Ⅰ. Describe what this PR does
Jindo Dataload support setting affinity. #2731

### CODE REVIEW

**Review by fengshunli — CHANGES_REQUESTED** [review]
image
Add null value judgment

**Comment by allenhaozi** [comment]
> image
> 
> Add null value judgment

Thank you for your review, which has been fixed
Next time you can comment directly in the code

**Review by frankleaf — APPROVED** [review]

**Review by frankleaf — APPROVED** [review]

**Comment by TrafalgarZZZ** [comment]
@allenhaozi please retry e2e test with a rebased branch. The "failed to parse platform" error is already fixed in #2736

**Review by cheyang — APPROVED** [review]

**Pull request merged**
