### PR TITLE
set GO111MODULE="on" in Makefile

### LINKED ISSUE #1282: [FEATURES] Enable GO111MODULE="on" when compiling
**What feature you'd like to add:**

The suggestion I would like to make is to enable the module environment.

**Why is this feature needed:**

I noticed that the documentation mentioned that we should develop under non-module environment.
I have tried compiling in the module environment and it still works.
Now that Golang v1.17 has been released, I believe most developers are more comfortable with the module environment.
Therefore, the suggestion I would like to make is to enable module environment.

### PR DESCRIPTION
**Pull request by wangao1236**
### Ⅰ. Describe what this PR does

set GO111MODULE="on" in Makefile.

### Ⅱ. Does this pull request fix one issue?

fixes #1282 

### Ⅴ. Special notes for reviews

### CODE REVIEW

**Comment by cheyang** [comment]
@wangao1236 Thank you for contribution! I suggest to make it configurable and make it `off` as default mode to make it sure it's not breaking change for other developers.

**Comment by wangao1236** [comment]
> @wangao1236 Thank you for contribution! I suggest to make it configurable and make it `off` as default mode to make it sure it's not breaking change for other developers.

OK，I'll improve it. Thanks~

**Comment by wangao1236** [comment]
> @wangao1236 Thank you for contribution! I suggest to make it configurable and make it `off` as default mode to make it sure it's not breaking change for other developers.

I have corrected it, thanks~

**Comment by cheyang** [comment]
Please fix DCO. thanks.

**Comment by wangao1236** [comment]
> Please fix DCO. thanks.

Ok，I have corrected it.

**Review by cheyang — APPROVED** [review]

**Pull request merged**
