### PR TITLE
clean-up: remove unused functions

### LINKED ISSUE #991: [FEATURES] Dataset nodeAffinity should support matchFields
**What feature you'd like to add:**
For now, Fluid allow `nodeAffinity.required.nodeSelectorTerms[i].matchFields` to be defined in Dataset while it is ignored and takes no effect.

Dataset nodeAffinity should support matchFields like this:
```yaml
nodeAffinity:
  required:
    nodeSelectorTerms:
      - matchFields:
        - key: metadata.name
           operator: In
           values:
           - target-host-name
```

**Why is this feature needed:**
To make affinity fields of Dataset be consistent with affinity fields of Pods.

This is useful when users want to deploy Runtimes on some specific hosts.

### PR DESCRIPTION
**Pull request by omerap12**
### Ⅰ. Describe what this PR does
Remove unused functions.

### Ⅱ. Does this pull request fix one issue?

Refer to this comment: https://github.com/fluid-cloudnative/fluid/issues/991#issuecomment-2309242663

fixes #991 

### Ⅴ. Special notes for reviews

### CODE REVIEW

**Comment by omerap12** [comment]
@TrafalgarZZZ, would you like me to squash my commits?

**Comment by TrafalgarZZZ** [comment]
> @TrafalgarZZZ, would you like me to squash my commits?

We will "Squash and merge" your PR to `master` branch so it's okay.

**Review by TrafalgarZZZ — COMMENTED** [review]
Thanks @omerap12 for the PR! LGTM!
/lgtm

@cheyang Please take a look and merge it if there's no further comments

**Review by cheyang — APPROVED** [review]
/lgtm
/approve

**Comment by cheyang** [comment]
> Thanks @omerap12 for the PR! LGTM! /lgtm
> 
> @cheyang Please take a look and merge it if there's no further comments

LGTM. Thanks @omerap12 and @TrafalgarZZZ

**Comment by omerap12** [comment]
> > Thanks @omerap12 for the PR! LGTM! /lgtm
> 
> > 
> 
> > @cheyang Please take a look and merge it if there's no further comments
> 
> 
> 
> LGTM. Thanks @omerap12 and @TrafalgarZZZ 
> 
> 

No problem at all. Please ping me if you have any more issues for me to solve 😀

**Pull request merged**
