### PR TITLE
Fix license in file pkg/csi/updatedbconf/updatedbconf.go

### PR DESCRIPTION
**Pull request by orange-322**
### Ⅰ. Describe what this PR does:
This pr is to add copyright in pkg/csi/updatedbconf/updatedbconf.go

### CODE REVIEW

**Comment by cheyang** [comment]
@orange-322 please fix DCO issue. thanks.

**Comment by TrafalgarZZZ** [comment]
/retitle Fix license in file `pkg/csi/updatedbconf/updatedbconf.go`

**Comment by orange-322** [comment]
> /retitle Fix license in file pkg/csi/updatedbconf/updatedbconf.go

I have done this in the latest version, both copyright and license,what need I do next?

**Comment by TrafalgarZZZ** [comment]
> I have done this in the latest version, both copyright and license,what need I do next?

No more effort needed. Thx for fixing this. It's just a command for the community robot

/retitle Fix license in file pkg/csi/updatedbconf/updatedbconf.go
/lgtm
/approve

**Review by TrafalgarZZZ — APPROVED** [review]

**Pull request merged**
