### PR TITLE
Add helm version option in Makefile

### LINKED ISSUE #3307: [FEATURES]Make helm and kubectl version configurable in Makefile
**What feature you'd like to add:**

Currently, we configure kubectl and helm version in Dockerfile. We'd like to put it as docker args in the Makefile so we can change it in one place. 

**Why is this feature needed:**

### PR DESCRIPTION
**Pull request by omerap12**
### Ⅰ. Describe what this PR does
Add an option to set the helm version in Makefile ( one place ).

### Ⅱ. Does this pull request fix one issue?

fixes #3307

### Ⅳ. Describe how to verify it
Run make build using the Makefile and check it works.

### Ⅴ. Special notes for reviews

### CODE REVIEW

**Comment by cheyang** [comment]
@omerap12 thanks very much for your contribution!

**Comment by omerap12** [comment]
> @omerap12 thanks very much for your contribution!

No worries at all! I’m looking forward to tackling more issues in the future.

**Review by cheyang — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
