### PR TITLE
Corrected situation 3 at file 'constant.go' (there was Licence with c…

### PR DESCRIPTION
**Pull request by maksimphono**
…opyrights, but copyright time was incorrect)

### Ⅰ. Describe what this PR does
This PR is added for: 修改在 "constant.go" 文件里的错误。错误的种类是情况三（有Apache License的通告声明，也有Copyright，但Copyright时间有误）。已经修改好了。

### Ⅱ. Does this pull request fix one issue?

fixes #XXXX

### Ⅴ. Special notes for reviews

### CODE REVIEW

**Comment by LiYuhang9527** [comment]
look  good to me

**Comment by RongGu** [comment]
ok-to-test

**Review by RongGu — APPROVED** [review]
/approve

**Review by cheyang — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
