### PR TITLE
dataflow ensure the dependent operation was completed

### PR DESCRIPTION
**Pull request by xliuqq**
### Ⅰ. Describe what this PR does
dataflow ensure the dependent operation was completed.

### Ⅱ. Does this pull request fix one issue?

fixes #XXXX

### Ⅴ. Special notes for reviews

### CODE REVIEW

**Review by TrafalgarZZZ — COMMENTED** [review]
/lgtm

**Review by cheyang — APPROVED** [review]
/lgtm
/approve

**Review by TrafalgarZZZ — APPROVED** [review]

**Pull request merged**
