### PR TITLE
Refactor label keys in RuntimeInfo

### PR DESCRIPTION
**Pull request by omerap12**
### Ⅰ. Describe what this PR does
Refactor label key functions from the `Runtime` struct by moving them to the `utils` package.

### Ⅱ. Does this pull request fix one issue?

As part of #978, I'm splitting this into separate PRs, starting with refactoring label key functions from the `Runtime` struct and moving them to the `utils` package.

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.
No new tests are required, as the existing tests already cover the functionality and the function signatures remain unchanged.

### Ⅴ. Special notes for reviews

### CODE REVIEW

**Comment by cheyang** [comment]
@omerap12 thanks for your contribution. Could you check why the project check is failed? https://github.com/fluid-cloudnative/fluid/actions/runs/10376419144/job/28728332638?pr=4271

**Comment by omerap12** [comment]
> @omerap12 thanks for your contribution. Could you check why the project check is failed? https://github.com/fluid-cloudnative/fluid/actions/runs/10376419144/job/28728332638?pr=4271

Yes , of course

**Comment by omerap12** [comment]
Hey @cheyang , fixed . ( lint errors don't related to me I think)

**Review by TrafalgarZZZ — COMMENTED** [review]
/lgtm
LGTM and thank you for your great refactoring @omerap12 !

BTW, @cheyang  do we have any plan to remove codes related to such deprecated labels? It has been several published versions since we deprecated them. I think now it would be okay to remove them.

**Comment by omerap12** [comment]
Sure no problem @TrafalgarZZZ :)

**Comment by cheyang** [comment]
> /lgtm LGTM and thank you for your great refactoring @omerap12 !
> 
> BTW, @cheyang do we have any plan to remove codes related to such deprecated labels? It has been several published versions since we deprecated them. I think now it would be okay to remove them.

Thank you for your suggestion. It's fine to remove them after v1.0 releases.

**Comment by cheyang** [comment]
@omerap12 Please fix the project check /lint :https://github.com/fluid-cloudnative/fluid/actions/runs/10393294698/job/28780447009?pr=4271

**Comment by omerap12** [comment]
@cheyang  , done

**Review by cheyang — APPROVED** [review]
/lgtm
/approve

**Comment by cheyang** [comment]
Thanks very much @omerap12  .

**Pull request merged**
