### PR TITLE
fix images cve

### PR DESCRIPTION
**Pull request by uniqueni**
Signed-off-by: Wang Ni <wangni@4paradigm.com>

### Ⅰ. Describe what this PR does

fix this issue https://github.com/fluid-cloudnative/fluid/issues/1316

### Ⅴ. Special notes for reviews

### CODE REVIEW

**Comment by uniqueni** [comment]
I not sure that the upgrade will not cause other problems, so this pr need to be reviewed，please

**Comment by cheyang** [comment]
> I not sure that the upgrade will not cause other problems, so this pr need to be reviewed，please

I took a look into the changes go.mod, generally it looks fine. And we also have UT to avoid breaking change. My proposal is that we can create docker image for this change, if you have time to test it. we will be very appreciated. Thanks.

**Comment by uniqueni** [comment]
> > I not sure that the upgrade will not cause other problems, so this pr need to be reviewed，please
> 
> I took a look into the changes go.mod, generally it looks fine. And we also have UT to avoid breaking change. My proposal is that we can create docker image for this change, if you have time to test it. we will be very appreciated. Thanks.

ok I can test it after you created these docker images

**Comment by cheyang** [comment]
The image tag is `v0.7.0-70b4e7a`.  Please have a try. If you encounter any problems, please let me know. Thanks.

**Comment by cheyang** [comment]
@uniqueni if you have any update, please let me know. Thanks.

**Comment by uniqueni** [comment]
> @uniqueni if you have any update, please let me know. Thanks.

sorry, just saw this news , i will test this image, if i have some problem, i will let you know

**Comment by cheyang** [comment]
> > @uniqueni if you have any update, please let me know. Thanks.
> 
> sorry, just saw this news , i will test this image, if i have some problem, i will let you know

No problem.

**Comment by uniqueni** [comment]
>

**Comment by uniqueni** [comment]
> > > @uniqueni if you have any update, please let me know. Thanks.
> > 
> > 
> > sorry, just saw this news , i will test this image, if i have some problem, i will let you know
> 
> No problem.

this images is available,thx

**Pull request closed without merging**
