### PR TITLE
spoken corrected

### LINKED ISSUE #3830: [DOC] correct errors in cmd\jindo\app\jindo.go
**Provide a link to that doc page:**
https://github.com/fluid-cloudnative/fluid/blob/master/cmd/jindo/app/jindo.go
**What is the defect and your suggestions on improvement:**
cmd\jindo\app\jindo.go:100:144: corrected "reconcilation" to "reconciliation"
cmd\jindo\app\jindo.go:101:137: corrected "reconcilation" to "reconciliation"

### PR DESCRIPTION
**Pull request by spark4862**
### Ⅰ. Describe what this PR does
cmd\jindo\app\jindo.go:100:144: corrected "reconcilation" to "reconciliation"
cmd\jindo\app\jindo.go:101:137: corrected "reconcilation" to "reconciliation"

### Ⅱ. Does this pull request fix one issue?

fixes #3830

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.
nothing

### Ⅳ. Describe how to verify it
just look at 

### Ⅴ. Special notes for reviews
nothing

### CODE REVIEW

**Comment by LiYuhang9527** [comment]
look good to me

**Review by RongGu — APPROVED** [review]
/approve

**Review by cheyang — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
