### PR TITLE
cleanup: Remove unnecessary comment

### LINKED ISSUE #4291: [FEATURES] Handle cases where FullnameOverride is too long
What feature you'd like to add:
Currently, we are not handling scenarios where FullnameOverride exceeds 63 characters.

Why is this feature needed:
For example: [transform.go Line 49](https://github.com/fluid-cloudnative/fluid/blob/master/pkg/ddc/thin/transform.go#L49).
Handling longer FullnameOverride values is essential to avoid potential issues such as naming conflicts or deployment failures in Kubernetes.

I can implement this myself. (Should we cut it at 63 characters, or consider another approach?)

### PR DESCRIPTION
**Pull request by omerap12**
### Ⅰ. Describe what this PR does
Remove TODO comment which already implemented

### Ⅱ. Does this pull request fix one issue?

fixes #4291

### Ⅴ. Special notes for reviews

### CODE REVIEW

**Comment by xliuqq** [comment]
@cheyang The `_helper.tpl` in runtime chart's directory has already truncate `fullnameOverride` to a maximum of 63 characters, here is the code.
https://github.com/fluid-cloudnative/fluid/blob/6ff32f9467254ad3d3bd2c2d4a6f77335ca12f87/charts/alluxio/templates/_helpers.tpl#L16
Should we do it again ?

**Comment by cheyang** [comment]
> @cheyang The `_helper.tpl` in runtime chart's directory has already truncate `fullnameOverride` to a maximum of 63 characters, here is the code.
> 
> https://github.com/fluid-cloudnative/fluid/blob/6ff32f9467254ad3d3bd2c2d4a6f77335ca12f87/charts/alluxio/templates/_helpers.tpl#L16
> 
> 
> Should we do it again ?
Good Catch.  FYI @omerap12 , I think we can just remove TODO.

**Comment by omerap12** [comment]
@cheyang  done :)

**Review by cheyang — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
