### PR TITLE
Fix check workers healthy

### PR DESCRIPTION
**Pull request by iluoeli**
### Ⅰ. Describe what this PR does
fixes issue #631 

### Ⅱ. Does this pull request fix one issue?

fixes issue #631 

### Ⅴ. Special notes for reviews

### CODE REVIEW

**Review by TrafalgarZZZ — APPROVED** [review]
/lgtm

**Comment by TrafalgarZZZ** [comment]
With this patch, maybe we can remove the [limit](https://github.com/fluid-cloudnative/fluid/blob/master/charts/fluid/fluid/crds/data.fluid.io_alluxioruntimes.yaml#L278) set for `AlluxioRuntime.spec.replicas`?

**Comment by iluoeli** [comment]
> With this patch, maybe we can remove the [limit](https://github.com/fluid-cloudnative/fluid/blob/master/charts/fluid/fluid/crds/data.fluid.io_alluxioruntimes.yaml#L278) set for `AlluxioRuntime.spec.replicas`?

I wonder if there are any situations users need to set replicas=0 ? Currently, I just treat replicas=0 as a corner case, and suppress this error. If users set an unexpected replicas (e.g. zero) by accident, they may be not aware of this mistake, because Fluid will  not return error now.

**Comment by cheyang** [comment]
> > With this patch, maybe we can remove the [limit](https://github.com/fluid-cloudnative/fluid/blob/master/charts/fluid/fluid/crds/data.fluid.io_alluxioruntimes.yaml#L278) set for `AlluxioRuntime.spec.replicas`?
> 
> I wonder if there are any situations users need to set replicas=0 ? Currently, I just treat replicas=0 as a corner case, and suppress this error. If users set an unexpected replicas (e.g. zero) by accident, they may be not aware of this mistake, because Fluid will not return error now.

In Knative, it's an interesting term: scale down to zero.  Because usually there are many datasets in the same Kubernetes cluster, we need freeze the dataset when no one is using it.

**Comment by iluoeli** [comment]
> With this patch, maybe we can remove the [limit](https://github.com/fluid-cloudnative/fluid/blob/master/charts/fluid/fluid/crds/data.fluid.io_alluxioruntimes.yaml#L278) set for `AlluxioRuntime.spec.replicas`?
> 
> I agree. @iluoeli did you test this?

I tested your case #631, and it works fine.

**Comment by iluoeli** [comment]
> > > With this patch, maybe we can remove the [limit](https://github.com/fluid-cloudnative/fluid/blob/master/charts/fluid/fluid/crds/data.fluid.io_alluxioruntimes.yaml#L278) set for `AlluxioRuntime.spec.replicas`?
> > 
> > 
> > I wonder if there are any situations users need to set replicas=0 ? Currently, I just treat replicas=0 as a corner case, and suppress this error. If users set an unexpected replicas (e.g. zero) by accident, they may be not aware of this mistake, because Fluid will not return error now.
> 
> In Knative, it's an interesting term: scale down to zero. Because usually there are many datasets in the same Kubernetes cluster, we need freeze the dataset when no one is using it.

That's a good point!

**Review by cheyang — APPROVED** [review]

**Pull request merged**
