### PR TITLE
fix the bug set Port Properties In alluxioRuntime, alluxio Pod crash

### PR DESCRIPTION
**Pull request by hahchenchen**
### Ⅰ. Describe what this PR does
fix the bug set Port Properties In alluxioRuntime, alluxio Pod crash

### Ⅱ. Does this pull request fix one issue?
fix bug: #2262

### CODE REVIEW

**Comment by cheyang** [comment]
@hahchenchen I'm very appreciated on your fix. It's cool!

If possible, could you please insert this logic into `e.allocatePorts`


https://github.com/fluid-cloudnative/fluid/blob/b4bf494c37021179cfa90a0090eba3e02397beea/pkg/ddc/alluxio/transform.go#L97-L103

**Comment by hahchenchen** [comment]
>

**Comment by hahchenchen** [comment]
@cheyang OK, already inserted.

**Review by cheyang — APPROVED** [review]

**Comment by cheyang** [comment]
@hahchenchen thanks very much for your contribution! Look forward to your next PR.

**Pull request merged**
