### PR TITLE
update: translate the doc of arm into english

### PR DESCRIPTION
**Pull request by wang-mask**
### Ⅰ. Describe what this PR does
    Translate the doc of arm into English.

### Ⅴ. Special notes for reviews

### CODE REVIEW

**Review by cheyang — APPROVED** [review]

**Comment by cheyang** [comment]
@odidev We already support arm64 in v0.8.0. Here is the doc, please check it. And if you want to polish it, it's welcomed.

**Comment by odidev** [comment]
Hi @cheyang , thank you for sharing the news. 

I worked with v0.8.0, following the docs [here](https://github.com/fluid-cloudnative/fluid/blob/master/docs/en/samples/arm64.md), and found some issues. 

As stated [here](https://github.com/fluid-cloudnative/fluid/blob/master/docs/en/samples/arm64.md#change-the-image-version-in-helm-chart), there is no directory " **fluid-cloudnative/fluid/fluid** ". I think you mean to mention “**fluid-cloudnative/fluid/charts/fluid/fluid**”? 

Next, I cloned the repo, checked out v0.8.0, and installed fluid using helm as below: 
~~~ 
$ helm install fluid charts/fluid/fluid 
~~~ 

But the error comes up saying: 
~~~ 
Error: INSTALLATION FAILED: namespaces "fluid-system" not found 
~~~ 

However, there is already a namespace ‘’fluid-system” mentioned in [Charts.yaml.](https://github.com/fluid-cloudnative/fluid/blob/master/charts/fluid/fluid/Chart.yaml) 

Also, I noticed that in the ARM64 docs [here](https://github.com/fluid-cloudnative/fluid/blob/master/docs/en/samples/arm64.md#installation), helm is installed in the default namespace in your logs, so I am confused, why my fluid installation using helm is searching for the namespace. 

I tried removing “namespace: fluid-system” in charts/fluid/fluid/Charts.yaml, but it did not help.

**Comment by odidev** [comment]
Also, unit test is failing on ARM64 even in v0.8.0 and the master branch. The reason is not clear to me. I can see various " SIGILL: illegal instruction” errors in the logs. 

Kindly find my unit test logs here for ARM64:  [fluid_unittest_logs.txt](https://github.com/fluid-cloudnative/fluid/files/9607618/fluid_unittest_logs.txt)

Can you please provide some pointers on why the tests are failing, and the namespace issue with fluid installation using helm?

**Comment by wang-mask** [comment]
I will fix the doc probles soon. The path is indeed wrong and it is must to create the fluid-system ns before install fluid.

**Comment by odidev** [comment]
Thank you for the PR to update docs. 

I followed the commands and my dataset `jfsdemo` fails to bound to the runtime. 

Instead of building my own multi-arch docker images, I used the tag “[v0.8.0-e730b87](https://hub.docker.com/layers/fluidcloudnative/juicefsruntime-controller/v0.8.0-e730b87/images/sha256-26fe1c9eac4b3047d365d99e25ddd18ac803f85dcbbbc5a40354a9ae2f5fa72b?context=explore)” available at dockerhub. This tag already supports multi-arch platform. 

 

But if I check dataset `jfsdemo `after deploying the runtime, I get the below output: 
~~~ 
$ kubectl get dataset jfsdemo 

NAME      UFS TOTAL SIZE   CACHED   CACHE CAPACITY   CACHED PERCENTAGE   PHASE      AGE 
jfsdemo                                                                  NotBound   17h 
~~~ 

 

Also, It seems everything in the namespace `fluid-system` is running fine, as shown below: 
~~~ 
$ kubectl get all -n fluid-system 

NAME                                            READY   STATUS    RESTARTS      AGE 
pod/csi-nodeplugin-fluid-cmv4d                  2/2     Running   2 (16h ago)   17h 
pod/dataset-controller-69c4b6fcf9-sgwmr         1/1     Running   1 (16h ago)   17h 
pod/fluid-webhook-79f78dbbd9-v24g5              1/1     Running   1 (16h ago)   17h 
pod/fluidapp-controller-6b49b9f5f9-vsjm8        1/1     Running   1 (16h ago)   17h 
pod/juicefsruntime-controller-7c78b44bf-fp9ht   1/1     Running   1 (44s ago)   17h 

  
NAME                                  TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE 
service/fluid-pod-admission-webhook   ClusterIP   10.111.221.244   <none>        9443/TCP   17h 
  

NAME                                  DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE 
daemonset.apps/csi-nodeplugin-fluid   1         1         1       1            1           <none>          17h 
  

NAME                                        READY   UP-TO-DATE   AVAILABLE   AGE 
deployment.apps/alluxioruntime-controller   0/0     0            0           17h 
deployment.apps/dataset-controller          1/1     1            1           17h 
deployment.apps/fluid-webhook               1/1     1            1           17h 
deployment.apps/fluidapp-controller         1/1     1            1           17h 
deployment.apps/goosefsruntime-controller   0/0     0            0           17h 
deployment.apps/jindoruntime-controller     0/0     0            0           17h 
deployment.apps/juicefsruntime-controller   1/1     1            1           17h 

  
NAME                                                   DESIRED   CURRENT   READY   AGE 
replicaset.apps/alluxioruntime-controller-7f879c9bb5   0         0         0       17h 
replicaset.apps/dataset-controller-69c4b6fcf9          1         1         1       17h 
replicaset.apps/fluid-webhook-79f78dbbd9               1         1         1       17h 
replicaset.apps/fluidapp-controller-6b49b9f5f9         1         1         1       17h 
replicaset.apps/goosefsruntime-controller-7f64d7fc88   0         0         0       17h 
replicaset.apps/jindoruntime-controller-67747d876c     0         0         0       17h 
replicaset.apps/juicefsruntime-controller-7c78b44bf    1         1         1       17h 
~~~ 

This issue is common on both x64 and ARM64 platforms.

**Comment by wang-mask** [comment]
I think it is becase the fail of runtime. You can run
'''
$ kubectl get juicefsruntime
$ kubectl get pods
'''
To see the status of runtime and runtime worker pod. The JuicsFS needs metadata engine (e.g. Redis) and object storage services (such as MinIO).
And i will translate the juicefs-setup doc to english soon.

**Comment by odidev** [comment]
Okay. Below is the status of the runtime and the pods: 
```
$ kubectl get juicefsruntime 

NAME      WORKER PHASE   FUSE PHASE   AGE 
jfsdemo   Ready                       16m 
```

```
$ kubectl get juicefs jfsdemo 

NAME      WORKER PHASE   FUSE PHASE   AGE 
jfsdemo   Ready                       16m 
```

```
$ kubectl get po |grep demo 

demo-app           0/1     Pending   0             13m 
jfsdemo-worker-0   1/1     Running   9 (28s ago)   15m 
```


> The JuicsFS needs metadata engine (e.g. Redis) and object storage services (such as MinIO). 

Before creating dataset, I created secret with redis and minio as below: 
~~~ 
kubectl create secret generic jfs-secret \ 
    --from-literal=metaurl=redis://redis:6379/0 \ 
    --from-literal=access-key=minioadmin \ 
    --from-literal=secret-key=minioadmin 
~~~

**Comment by cheyang** [comment]
Could you please upload the log of juicefsruntime-controller-7c78b44bf-fp9ht? Thanks.

**Comment by zwwhdls** [comment]
Hi, it seems juicefs worker is not ready from log. `jfsdemo-worker-0` pod keeps restarting. I guess it was oomed . Can you provide its yaml by `kubectl get po jfsdemo-worker-0 -oyaml` and its log by `kubectl logs jfsdemo-worker-0`?

**Pull request merged**
