### PR TITLE
modify "seperates" to "separates"

### PR DESCRIPTION
**Pull request by AGCWH666**
### Ⅰ. Describe what this PR does
 docs\en\samples\juicefs_for_s3.md:3:79: corrected "seperates" to "separates"

### Ⅱ. Does this pull request fix one issue?

fixes #XXXX

### Ⅴ. Special notes for reviews

### CODE REVIEW

**Comment by LiYuhang9527** [comment]
you should add -s when you use command "git commit".  please pr again

**Review by cheyang — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
