### PR TITLE
add Apache 2.0 license to jindo.go

### LINKED ISSUE #1191: [DOC]Add Apache 2.0 license to pkg/common/jindo.go
**Provide a link to that doc page:**
https://github.com/fluid-cloudnative/fluid/blob/master/pkg/common/jindo.go
**What is the defect and your suggestions on improvement:**
There is no license statement for this file.
Apache 2.0 license should be added at the beginning.

### PR DESCRIPTION
**Pull request by gl-up**
### Ⅰ. Describe what this PR does
This PR is to add Apache 2.0 license

### Ⅱ. Does this pull request fix one issue?

fixes #1191 
### Ⅴ. Special notes for reviews

### CODE REVIEW

**Comment by gl-up** [comment]
This PR is to add Apache 2.0 license to pkg/common/jindo.go

**Comment by gl-up** [comment]
This PR is to add Apache 2.0 license to pkg/common/jindo.go

**Comment by gl-up** [comment]
This PR is to add Apache 2.0 license to pkg/common/jindo.go

**Comment by cheyang** [comment]
Please fix the DCO warning.

**Comment by gl-up** [comment]
My guess is that because I made my email private, DCO cannot know about guolang1997@126.com

**Review by cheyang — APPROVED** [review]

**Pull request merged**
