### PR TITLE
Use Variables for simplify edits and enhance readability.

### PR DESCRIPTION
**Pull request by omerap12**
### Ⅰ. Describe what this PR does
1. Variable reorganization: Grouped related variables together for better clarity and easier maintenance.
2. Enhanced architecture support.
3. Standardized Docker build options.
4. Consolidated build targets: Streamlined the definition of build targets for various controllers, reducing repetition in the Makefile.
5. Improved multi-architecture support: Added Docker buildx targets to facilitate building for multiple architectures in a single command.
6. Standardized naming conventions: Adopted more consistent naming for targets and variables throughout the Makefile.
8. Enhanced modularity: Separated some functionalities into distinct targets, making the Makefile more modular and easier to extend.

### Ⅱ. Does this pull request fix one issue?

Part of  #4297 

### Ⅴ. Special notes for reviews

### CODE REVIEW

**Comment by omerap12** [comment]
@Syspretor, if valid Ill work on number 2 ( Phony Targets )

**Comment by Syspretor** [comment]
@omerap12 Thank you very much for this PR. The classification and organization of variable definitions is great, but there are some areas where we hope to improve. First of all, ensuring that all modules in the Makefile execute successfully is a priority in the optimization work for the Makefile. During my testing, I found some typos and syntax issues that broke this, such as the variable definition for DOCKER_PLATFORM on line 28, and a typo regarding the -f flag on line 231, among similar issues. So please try running the commands included in the Makefile to ensure they still work smoothly.

**Comment by omerap12** [comment]
> @omerap12 Thank you very much for this PR. The classification and organization of variable definitions is great, but there are some areas where we hope to improve. First of all, ensuring that all modules in the Makefile execute successfully is a priority in the optimization work for the Makefile. During my testing, I found some typos and syntax issues that broke this, such as the variable definition for DOCKER_PLATFORM on line 28, and a typo regarding the -f flag on line 231, among similar issues. So please try running the commands included in the Makefile to ensure they still work smoothly.

Got it. Ill test it myself then. Thanks for your review :)

**Review by TrafalgarZZZ — COMMENTED** [review]
@omerap12 I made some minor changes to make Github Actions work with the latest Makefile. The PR LGTM, thanks for making it much more clear. 
/lgtm

**Comment by omerap12** [comment]
> @omerap12 I made some minor changes to make Github Actions work with the latest Makefile. The PR LGTM, thanks for making it much more clear. /lgtm

No worries, I’m planning to enhance it further :)

**Review by TrafalgarZZZ — APPROVED** [review]

**Review by cheyang — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
