### PR TITLE
Add or standardize license information

### PR DESCRIPTION
**Pull request by poiu144**
### Ⅰ. Describe what this PR does
This pr is to add specifications for License Information at fluid/pkg/controllers/v1alpha1/jindo/implement.go:2

### Ⅱ. Does this pull request fix one issue?

fixes #XXXX

### Ⅴ. Special notes for reviews

### CODE REVIEW

**Comment by LiYuhang9527** [comment]
look good to me

**Review by RongGu — APPROVED** [review]
/approve

**Pull request merged**
