### PR TITLE
Bind all reconcile loops with limited context.Context

### LINKED ISSUE #1144: [FEATURES] bind all reconcile loops with limited context.Context
**What feature you'd like to add:**

[feat: bind all reconcile loops with limited context.Context](https://github.com/kubernetes-sigs/controller-runtime/issues/798)
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/690/files

**Why is this feature needed:**

### PR DESCRIPTION
**Pull request by omerap12**
### Ⅰ. Describe what this PR does
Adds a context timeout mechanism to all controllers' `Reconcile` functions.

### Ⅱ. Does this pull request fix one issue?

fixes #1144

### Ⅴ. Special notes for reviews
1. Timeout Value: Please verify that the 10-minute timeout duration is appropriate for the reconciliation process.
2. Logging Suggestion: Consider adding logs to the reconcile function that include the timeout value for better traceability.

### CODE REVIEW

**Review by TrafalgarZZZ — COMMENTED** [review]
Sorry for my late reply. Thanks for making this and I have just one comment for the PR: Moving limited context.Context to `func ReconcileInternal()` looks better to me, because most reconcilation logic resides in it and all the runtime controllers reuse the function.

**Comment by omerap12** [comment]
Hey @TrafalgarZZZ , thanks for your review. Sure I'll adjust the code.
one question, do all runtimes should have the same limited amount of time?

**Comment by TrafalgarZZZ** [comment]
> Hey @TrafalgarZZZ , thanks for your review. Sure I'll adjust the code. one question, do all runtimes should have the same limited amount of time?

@omerap12 I think 10-minute timeout duration is pretty enough for all the runtimes, so it's okay for all runtimes to have the same limited amount of time.

**Review by TrafalgarZZZ — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
