### PR TITLE
Update operation_helm.go

### PR DESCRIPTION
**Pull request by rodestexas**
modify copyright time

### Ⅰ. Describe what this PR does
This pr is to modify copyright time of the Apache License in /pkg/ddc/base/operation_helm.go

### Ⅱ. Does this pull request fix one issue?

fixes #XXXX

### Ⅴ. Special notes for reviews

### CODE REVIEW

**Comment by LiYuhang9527** [comment]
you should add -s when you use command "git commit"

**Comment by rodestexas** [comment]
> you should add -s when you use command "git commit"

I updated my task and used "git commit" with -s again.

**Review by cheyang — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
